[package]
name = "chip8rs"
version = "0.1.0"
edition = "2021"
description = "Chip8 emulator"
license = "ISC"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
