name: Rust

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install SDL2
        run: sudo apt install libsdl2-dev
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
